version: '2.1'

services: 
    app:
      build: .
      depends_on:
          db:
           condition: service_healthy
      environment:
          PORT: 3000
          BD_HOST: db
          BD_PORT: 3306 
          BD_USER: root 
          BD_PASSWORD: root
          BD_NAME: agenda
          BD_SYNC: '${BD_SYNC:-true}'
      command:  npm run dev
      ports:
         - "3000:3000"
         - "9229:9229"
      volumes:
        - .:/usr/app/

    db:
        container_name: 'database-node'
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password 
        volumes: 
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql 
        ports: 
          - '3308:3306'
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - TZ=America/Sao_Paulo
        healthcheck:
          test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
          interval: 2s
          timeout: 30s
          retries: 15
